configuration-set.active=web-app-epam

# Task 1 - EPAM.com UI tests (Chrome, latest version)
configuration-set.web-app-epam.profiles=web/desktop/chrome
configuration-set.web-app-epam.suites=web_app_epam
configuration-set.web-app-epam.environments=

# Task 2 - Demo e-shop UI tests (Chrome, latest version)
configuration-set.web-app-shop.profiles=web/desktop/chrome
configuration-set.web-app-shop.suites=web_app_shop
configuration-set.web-app-shop.environments=

# Task 3 - Petstore REST API tests
configuration-set.rest-api-petstore.profiles=
configuration-set.rest-api-petstore.suites=rest_api_petstore
configuration-set.rest-api-petstore.environments=
